spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test
#    username: test
#    password: test
#    driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /console

server:
  port: 8081